--ozone-platform=wayland
--ozone-platform-hint=auto
--enable-features=TouchpadOverscrollHistoryNavigation,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder,VaapiVideoDecoder,HeliumMiddleClickAutoscroll,ExtensionsOnChromeUrls,ExtensionsOnExtensionUrls
