# set on macos:
# launchctl setenv NEOVIDE_FRAME buttonless

title-hidden = true
tabs = false

[font]
hinting = "full"
edging = "antialias"
normal = "JetBrainsMono Nerd Font"
# family = "JetBrainsMono Nerd Font"
size = 13
