#!/bin/bash

# originally from https://github.com/basecamp/omarchy/blob/master/bin/omarchy-webapp-launch
# omarchy:summary=Launch a URL as a web app in the default supported browser
# omarchy:args=<url>

browser=$(xdg-settings get default-web-browser)

case $browser in
google-chrome* | brave* | microsoft-edge* | opera* | vivaldi* | helium*) ;;
*) browser="chromium.desktop" ;;
esac

exec setsid uwsm-app -- $(sed -n 's/^Exec=\([^ ]*\).*/\1/p' {~/.local,~/.nix-profile,/usr}/share/applications/$browser 2>/dev/null | head -1) --app="$1" "${@:2}"
