quitOnTopLevelReturn: true
notARepository: skip
gui:
  scrollOffMargin: 5
  nerdFontsVersion: "3"
  showRandomTip: false
git:
  parseEmoji: true
os:
  edit: "$EDITOR {{filename}}"
  editAtLine: "$EDITOR +{{line}} {{filename}}"
