bind = CTRL, code:107, pass, class:com.obsproject.Studio

# minecraft
windowrule = tag +game, match:class Minecraft*
windowrule = match:class org.prismlauncher.PrismLauncher, float 1, center 1, size (monitor_w*0.35) (monitor_h*0.4)

# steam rules
windowrule = focus_on_activate off, no_initial_focus on, suppress_event activatefocus, match:class steam

# steam game rules
# note: yad is steam-tinker-launcher
windowrule = tag +game, match:class ^steam_app_\d+$
windowrule = tag +game, match:class gamescope
windowrule = tag +game, match:xdg_tag proton-game
windowrule = fullscreen 1, match:tag game
windowrule = monitor 1, match:tag game
windowrule = workspace 10, match:tag game
windowrule = workspace 9, match:class steam
windowrule = workspace 9, match:class yad
