windowrule = match:class org.prismlauncher.PrismLauncher, float 1, center 1, size (monitor_w*0.35) (monitor_h*0.4)
windowrule = match:class org.keepassxc.KeePassXC, float 1, center 1, size (monitor_w*0.35) (monitor_h*0.4)
