windowrule = match:class org.keepassxc.KeePassXC, float 0, center 1, size (monitor_w*0.35) (monitor_h*0.4)
windowrule = match:title Unlock Database - KeePassXC, float 1, no_initial_focus off, focus_on_activate on, stay_focused on
