bind = , PRINT, pass, class:^(com\.obsproject\.Studio)$
windowrule = monitor 2, match:class com.obsproject.Studio
windowrule = workspace 5, match:class com.obsproject.Studio
windowrule = match:title Projector - Preview, size 1920 1080
