bindd = SUPER, TAB, window management, exec, vicinae vicinae://extensions/vicinae/wm/switch-windows

layerrule {
    name = vicinae
    blur = on
    # blur_popups = on
    ignore_alpha = 0
    dim_around = on
    match:namespace = vicinae
}
