[settings]
experimental = true
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[bootstrap.repos]
"~/repos/dotfiles" = { url = "https://github.com/dokxid/dotfiles.git", ref = "main" }

[dotfiles]
"~/.dotfiles" = "~/repos/dotfiles"
"~/.config/mise/config.toml" = "~/repos/dotfiles/mise/config.toml"
