$mainMod = SUPER

scrolling {
    column_width = 0.75
    fullscreen_on_one_column = true
    follow_focus = false
    explicit_column_widths = 0.33, 0.5, 0.75, 0.9, 1.0        
    focus_fit_method = 0
}

# focus
# bind = $mainMod, LEFT, layoutmsg, focus l
# bind = $mainMod, RIGHT, layoutmsg, focus r
# bind = $mainMod, mouse_up, layoutmsg, focus r
# bind = $mainMod, mouse_down, layoutmsg, focus l

# reorder
bind = $mainMod CTRL, RIGHT, layoutmsg, swapcol r
bind = $mainMod CTRL, LEFT, layoutmsg, swapcol l
bind = $mainMod CTRL, mouse_up, layoutmsg, swapcol r
bind = $mainMod CTRL, mouse_down, layoutmsg, swapcol l

# colresize
bind = $mainMod SHIFT, A, layoutmsg, togglefit
bind = $mainMod CTRL, UP, layoutmsg, colresize +conf
bind = $mainMod CTRL, DOWN, layoutmsg, colresize -conf
bind = $mainMod CTRL, mouse_up, layoutmsg, colresize -conf
bind = $mainMod CTRL, mouse_down, layoutmsg, colresize +conf
