# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/ssh-agent.socket
env = fileManager,ghostty -e yazi
env = VISUAL,neovide
env = MESA_SHADER_CACHE_DIR,/home/dokxid/nvme/.cache
