# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # keyboard
  kb_layout = us
  kb_options = caps:super, ctrl:swap_lalt_lctl
  repeat_rate = 35
  repeat_delay = 300
  numlock_by_default = true

  # mouse
  force_no_accel = true
  follow_mouse = 1
  follow_mouse_threshold = 50
  sensitivity = 0

  # touchpad
  touchpad {
    natural_scroll = true
    clickfinger_behavior = true
    scroll_factor = 0.4
  }
}

cursor {
  hide_on_key_press = true
  no_warps = false
  warp_on_toggle_special = 0
}

misc {
  middle_click_paste = false
  allow_session_lock_restore = true
}

debug {
  disable_logs = false
}

binds {
  scroll_event_delay = 0 
}

windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2
