# constants
$activeBorderColor = rgba(33ccffee) rgba(00ff99ee) 45deg
$inactiveBorderColor = rgba(595959aa)

# mouse cursor
env = HYPRCURSOR_THEME,theme_mactahoe_dark
env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24

animations {
    animation = windows, 1, 0.8, default
    animation = workspaces, 1, 1.5, easeOutQuint, slidefadevert
}

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # gaps_in = 6
    # gaps_out = 10
    layout = scrolling
    # border_size = 2
    resize_on_border = true
    allow_tearing = false
    # col.active_border = $activeBorderColor
    # col.inactive_border = $inactiveBorderColor
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 20
}

# decoration:blur {
#     enabled = true
#     size = 4
#     passes = 2
#     noise = 0.15
# }

# decoration:shadow {
#     enabled = true
#     range = 8
#     render_power = 3
#     color = 0xe49bc8ff
#     color_inactive = 0x00c49bc8
# }

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    single_window_aspect_ratio = 4 3
}

input {
    float_switch_override_focus = 2
}

# misc {
#     initial_workspace_tracking = 2
# }
