# Change the default Omarchy look'n'feel

# mouse cursor
# env = HYPRCURSOR_THEME,theme_mactahoe_dark
# env = HYPRCURSOR_THEME,
# env = HYPRCURSOR_SIZE,24
env = XCURSOR_THEME,Adwaita
env = XCURSOR_SIZE,24

animations {
    animation = windows, 1, 0.8, default
    animation = workspaces, 1, 1.5, easeOutQuint, slidefadevert
}

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 6
    gaps_out = 10
    layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 20
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    single_window_aspect_ratio = 4 3
}

master {
    mfact = 0.65
    new_status = master
}

input {
    float_switch_override_focus = 2
}

misc {
    initial_workspace_tracking = 2
}
