-- Generated by Noctalia

local primary = "rgb(efb4e9)"
local surface = "rgb(171216)"
local secondary = "rgb(d9bfd3)"
local error = "rgb(ffb4ab)"

hl.layer_rule({
	name = "noctalia",
	match = {
		namespace = "^noctalia-(bar-.+|notification|dock|panel|attached-panel|osd)$",
	},
	no_anim = true,
	ignore_alpha = 0.5,
	blur = true,
	blur_popups = true,
})

hl.window_rule({
	match = { class = "dev.noctalia.Noctalia" },
	float = true,
	size = { 1080, 920 },
})

local function apply_theme()
	hl.config({
		general = {
			col = {
				active_border = primary,
				inactive_border = surface,
			},
		},

		group = {
			col = {
				border_active = secondary,
				border_inactive = surface,
				border_locked_active = error,
				border_locked_inactive = surface,
			},

			groupbar = {
				col = {
					active = secondary,
					inactive = surface,
					locked_active = error,
					locked_inactive = surface,
				},
			},
		},
	})
end

return {
	colors = {
		primary = primary,
		surface = surface,
		secondary = secondary,
		error = error,
	},
	apply_theme = apply_theme,
}
