$mainMod = SUPER

# unbind default bindings
unbind = $mainMod, mouse_up           # active window cycling forw
unbind = $mainMod, mouse_down         # active window cycling back
unbind = $mainMod CTRL, N                # night light default bind 
unbind = $mainMod, BACKSPACE             # toggle transparency
unbind = $mainMod, W                     # kill window
unbind = $mainMod, F                     # toggle fullscreen
unbind = $mainMod, E                     # toggle fullscreen
unbind = $mainMod, TAB                # next existing workspace
unbind = $mainMod SHIFT, TAB          # prev existing workspace
unbind = $mainMod ALT, SPACE          # omarch-menu
unbind = , PRINT                      # screenshot default bind
unbind = SHIFT, PRINT                 # screenshot to clipboard default bind
unbind = ALT, PRINT                   # screenrecord default bind
unbind = $mainMod, PRINT                 # color picker default bind
unbind = $mainMod, LEFT               # go to left tile
unbind = $mainMod, RIGHT              # go to right tile
unbind = $mainMod, UP                 # go to up tile
unbind = $mainMod, DOWN               # go to down tile
unbind = $mainMod CTRL, F             # pseudo fullscreen
# unbind = $mainMod, G                # group windows
unbind = $mainMod ALT, S                 # move to scratchpad default bind
unbind = $mainMod CTRL, T
unbind = $mainMod CTRL, E                # emoji picker
unbind = CTRL, SPACE                  # walker
unbind = $mainMod, SPACE                 # walker
unbind = $mainMod, Slash         # presentation mode
unbind = ALT, TAB # switch windows
unbind = SUPER SHIFT, code:10
unbind = SUPER SHIFT, code:11
unbind = SUPER SHIFT, code:12
unbind = SUPER SHIFT, code:13
unbind = SUPER SHIFT, code:14
unbind = SUPER SHIFT, code:15
unbind = SUPER SHIFT, code:16
unbind = SUPER SHIFT, code:17
unbind = SUPER SHIFT, code:18
unbind = SUPER SHIFT, code:19
unbind = SUPER SHIFT, code:10
unbind = SUPER SHIFT ALT, code:11
unbind = SUPER SHIFT ALT, code:12
unbind = SUPER SHIFT ALT, code:13
unbind = SUPER SHIFT ALT, code:14
unbind = SUPER SHIFT ALT, code:15
unbind = SUPER SHIFT ALT, code:16
unbind = SUPER SHIFT ALT, code:17
unbind = SUPER SHIFT ALT, code:18
unbind = SUPER SHIFT ALT, code:19
unbind = SUPER CTRL, O
unbind = SUPER, O
unbind = $mainMod SHIFT, SPACE
unbind = $mainMod CTRL, COMMA
unbind = $mainMod CTRL, SPACE
