### main display workspaces
# workspace 1
workspace = 1, persistent:true, monitor:DP-3, defaultName:1_default, layout:scrolling
windowrule = match:workspace name:1_default, float 0
# workspace 2
workspace = 2, persistent:true, monitor:DP-3, layout:dwindle
windowrule = match:workspace 2, float 0
# workspace 3
workspace = 3, persistent:true, monitor:DP-3, layout:dwindle
windowrule = match:workspace 3, float 1

### 2nd display workspaces
# workspace 4
workspace = 4, persistent:true, monitor:HDMI-A-1, defaultName:2_default, layout:scrolling
windowrule = match:workspace name:2_default, float 0
# workspace 5
workspace = 5, persistent:true, monitor:HDMI-A-1, layout:dwindle
windowrule = match:workspace 5, float 0
# workspace 6
workspace = 6, persistent:true, monitor:HDMI-A-1, layout:dwindle
windowrule = match:workspace 6, float 1

### special workspaces
# workspace 9
workspace = 9, monitor:DP-3, layout:dwindle     # steam
windowrule = match:workspace 9, float 1, center 1
# workspace 10
workspace = 10, monitor:DP-3, layout:dwindle    # fullscreen games
windowrule = match:workspace 10, float 1
# workspace = 10, border:false, rounding:false
# scratchpad
windowrule = match:workspace special:scratchpad, float 1, center 1

# dont tile xwayland applications
windowrule = match:xwayland false, float 0

# specific window rules
windowrule = match:class dragon-drop, float 1, pin 1, no_initial_focus 1
windowrule = match:class gimp, float 1
windowrule = match:tag floating-window, size (monitor_w*0.8) (monitor_h*0.8)

# set active/inactive opacity at the end
windowrule = opacity 1 0.9, match:tag default-opacity
windowrule = opacity 1.0 0.9, match:tag chromium-based-browser
windowrule = opacity 1.0 0.9, match:tag firefox-based-browser

# variables
misc {
  enable_swallow = true
  on_focus_under_fullscreen = 0
}
