workspace = 1, persistent:true, monitor:DP-3, defaultName:1_default, layout:scrolling
workspace = 2, persistent:true, monitor:DP-3, layout:dwindle
workspace = 3, persistent:true, monitor:DP-3, layout:dwindle
workspace = 9, monitor:DP-3, layout:dwindle
workspace = 10, monitor:DP-3, layout:dwindle
workspace = 4, persistent:true, monitor:HDMI-A-1, defaultName:2_default, layout:scrolling
workspace = 5, persistent:true, monitor:HDMI-A-1, layout:dwindle
workspace = 6, persistent:true, monitor:HDMI-A-1, layout:dwindle

# floating window rules (not on main workspaces)
windowrule = match:xwayland false, float 0
windowrule = match:workspace name:1_default, float 0
windowrule = match:workspace 2, float 0
windowrule = match:workspace 3, float 1
windowrule = match:workspace 9, float 1, center 1
windowrule = match:workspace 10, float 1
windowrule = match:workspace name:2_default, float 0
windowrule = match:workspace 5, float 0
windowrule = match:workspace 6, float 1
windowrule = match:workspace special:scratchpad, float 1, center 1

workspace = 10, border:false, rounding:false

windowrule = match:class dragon-drop, float 1, pin 1, no_initial_focus 1
windowrule = match:class gimp, float 1
windowrule = match:tag floating-window, size (monitor_w*0.8) (monitor_h*0.8)

# set active/inactive opacity at the end
windowrule = opacity 1 0.95, match:tag default-opacity

# variables
misc {
  enable_swallow = true
  on_focus_under_fullscreen = 0
}
