workspace = 1, persistent:true, monitor:DP-3, defaultName:1_default, layout:scrolling
workspace = 2, persistent:true, monitor:DP-3, layout:dwindle
workspace = 3, persistent:true, monitor:DP-3, layout:dwindle
workspace = 9, monitor:DP-3, layout:dwindle
workspace = 10, monitor:DP-3, layout:dwindle
workspace = 4, persistent:true, monitor:HDMI-A-1, defaultName:2_default, layout:scrolling
workspace = 5, persistent:true, monitor:HDMI-A-1, layout:dwindle
workspace = 6, persistent:true, monitor:HDMI-A-1, layout:dwindle

# floating window rules (not on main workspaces)
windowrule = match:xwayland false, size (monitor_w*0.5) (monitor_h*0.65)
windowrule = match:title Projector - Preview, size 1920 1080
windowrule = match:workspace name:1_default, float 0
windowrule = match:workspace 2, float 0
windowrule = match:workspace 3, float 1
windowrule = match:workspace 9, float 1
windowrule = match:workspace 10, float 1
windowrule = match:workspace name:2_default, float 0
windowrule = match:workspace 5, float 0
windowrule = match:workspace 6, float 1
windowrule = match:workspace special:scratchpad, float 1, center 1

# steam game rules
# note: yad is steam-tinker-launcher
windowrule = fullscreen 1, match:class ^steam_app_\d+$
windowrule = monitor 1, match:class ^steam_app_\d+$
windowrule = workspace 10, match:class ^steam_app_\d+$
windowrule = fullscreen 1, match:class gamescope
windowrule = monitor 1, match:class gamescope
windowrule = workspace 10, match:class gamescope
windowrule = fullscreen 1, match:xdg_tag proton-game
windowrule = monitor 1, match:xdg_tag proton-game
windowrule = workspace 10, match:xdg_tag proton-game
windowrule = workspace 9, match:class steam
windowrule = workspace 9, match:class yad
workspace = 10, border:false, rounding:false

windowrule = match:tag floating-window, size (monitor_w*0.8) (monitor_h*0.8)

# tag as game
windowrule = tag +game, match:class Minecraft*
windowrule = workspace 3, match:tag game

# set active/inactive opacity at the end
windowrule = opacity 1 0.95, match:tag default-opacity

# variables
misc {
  enable_swallow = true
  on_focus_under_fullscreen = 0
}
