[mgr]
append_keymap = []
prepend_keymap = [
  # vanilla yazi
  { on = "<Esc>", run = "quit", desc = "Quit Yazi" },
  { on = "<PageUp>", run = "seek -1", desc = "seek preview -1" },
  { on = "<PageDown>", run = "seek +1", desc = "seek preview +1" },
  { on = "?", run = "help", desc = "Show help" },
  { on = "!", for = "unix", run = "shell fish --block", desc = "open a shell here" },

  # utils
  { on = "R", run = "plugin recycle-bin", desc = "Open Recycle Bin menu" },
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = ["g", "t"], run = "plugin lazygit", desc = "run lazygit" },
  { on = "<C-n>", run = 'shell -- dragon-drop -x -i -T "$@"', desc = "drag and drop a file" },
  { on = "<C-l>", run = "plugin localsend", desc = "Send via LocalSend" },
  # { on = [".", "s"], run = "plugin what-size", desc = "Calc size of selection or cwd" },
  { on = "<C-r>", run = "plugin duck-radar", desc = "recent files" },

  # find / navigation
  { on = ["g", "r"], run = 'shell -- y emit cd "$(git rev-parse --show-toplevel)"', desc = "go to root git directory" },
  { on = ["g", "r"], run = "plugin yafg" },
  { on = "<C-p>", run = "plugin paste-navigate", desc = "navigate to path" },
  { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  { on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },

  # bookmarks
  { on = "b", run = "plugin whoosh jump_by_key", desc = "Jump bookmark by key" },
  { on = "<C-space>", run = "plugin whoosh jump_by_fzf", desc = "Direct fuzzy search for bookmarks" },
  { on = "<C-c>", run = "plugin whoosh jump_key_cc", desc = "jump to ~/.config" },
  { on = "<C-b>", run = "plugin whoosh jump_by_fzf", desc = "Jump bookmark by fzf" },
  { on = ["[", "a"], run = "plugin whoosh save", desc = "Add bookmark (hovered file/directory)" },
  { on = ["[", "A"], run = "plugin whoosh save_cwd", desc = "Add bookmark (current directory)" },
  { on = ["[", "d"], run = "plugin whoosh delete_by_key", desc = "Delete bookmark by key" },
  { on = ["[", "<delete>"], run = "plugin whoosh delete_by_fzf", desc = "Delete bookmarks by fzf (use TAB to select multiple)" },

  # projects / sessions
  { on = ["P", "s"], run = "plugin projects save", desc = "Save current project" },
  { on = ["P", "l"], run = "plugin projects load", desc = "Load project" },
  { on = ["P", "P"], run = "plugin projects load_last", desc = "Load last project" },
  { on = ["P", "d"], run = "plugin projects delete", desc = "Delete project" },
  { on = ["P", "D"], run = "plugin projects delete_all", desc = "Delete all projects" },
  { on = ["P", "m"], run = "plugin projects 'merge current'", desc = "Merge current tab to other projects" },
  { on = ["P", "M"], run = "plugin projects 'merge all'", desc = "Merge current project to other projects" },

  # view
  { on = ["e", "t"], run = "plugin eza-preview", desc = "Toggle tree/list dir preview" },
  { on = ["e", "-"], run = "plugin eza-preview inc-level", desc = "Increment tree level" },
  { on = ["e", "_"], run = "plugin eza-preview dec-level", desc = "Decrement tree level" },
  { on = ["e", "$"], run = "plugin eza-preview toggle-follow-symlinks", desc = "Toggle tree follow symlinks" },
  { on = ["e", "*"], run = "plugin eza-preview toggle-hidden", desc = "Toggle hidden files" },
  { on = ["e", "g", "i"], run = "plugin eza-preview toggle-git-ignore", desc = "Toggle .gitignore files" },
  { on = ["e", "g", "s"], run = "plugin eza-preview toggle-git-status", desc = "Toggle showing git status" },
  { on = "T", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },

  # tab navigation
  { on = "2", run = "plugin smart-switch 1", desc = "switch or create tab 2" },
  { on = "3", run = "plugin smart-switch 2", desc = "switch or create tab 3" },
  { on = "4", run = "plugin smart-switch 3", desc = "switch or create tab 4" },
]
