[mgr]
linemode = "size_and_mtime"
show_hidden = false
mouse_events = ["click", "scroll", "touch", "move", "drag"]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "video/*", use = "video" },
  { mime = "image/*", use = "image" },

  # { mime = "application/json", use = "edit" },
  { url = "*.json", use = "edit" },

  # Multiple openers for a single rule
  { url = "*.html", use = ["open", "edit"] },
]

[opener]
video = [
  { run = "mpv %s", orphan = true, for = "unix" },
  { run = "losslesscut %s", orphan = true, for = "unix" },
]
image = [
  { run = "satty -f %s", orphan = true, for = "unix" },
  { run = "imv %s", orphan = true, for = "unix" },
  { run = "krita %s", orphan = true, for = "unix" },
  { run = "gimp %s", orphan = true, for = "unix" },
]

edit = [{ run = 'neovide "$@" --frame none', block = false, for = "unix" }]
[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'

[[plugin.prepend_previewers]]
url = "*/"
run = "eza-preview"
